### ISSUE TITLE
Fill in README.md

### ISSUE THREAD

**Issue by Wedds** [java-practice-spb-2020/epam-ifmo-java-practice-2020-2#1]
Составить описание выбранного проекта.

**Comment by JustRevolt** [comment]
@Aeeee @nikaalin @ChirkinaTanya  Достаточно, или добавить еще что-то?

**Comment by ChirkinaTanya** [comment]
https://github.com/JustRevolt
Перевод
The system "Car rental"
Description
1. The Client selects a Car from the list of available.
2. The Client fills out the Order form, indicating passport data, the 
rental period.
3. The Client pays for the order.
4. The Administrator registers the return of the Car.
5. In case of damage to the Car, the Administrator enters information and forms a repair invoice.
6. The Administrator can reject the Order, indicating the reasons for the refusal.

**Comment by ChirkinaTanya** [comment]
@JustRevolt 
Перевод
The system "Car rental"
Description
1. The Client selects a Car from the list of available.
2. The Client fills out the Order form, indicating passport data, the 
rental period.
3. The Client pays for the order.
4. The Administrator registers the return of the Car.
5. In case of damage to the Car, the Administrator enters information and forms a repair invoice.
6. The Administrator can reject the Order, indicating the reasons for the refusal.
