### ISSUE TITLE
Create entity-relationship diagram

### ISSUE THREAD

**Issue by Wedds** [java-practice-spb-2020/epam-ifmo-java-practice-2020-2#2]
Необходимо продумать схему данных и нарисовать ее. Можно воспользоваться онлайн сервисом, например, https://dbdiagram.io/home

**Comment by a-deriabin** [comment]
![image](https://user-images.githubusercontent.com/2338967/73963780-f9af8700-4921-11ea-99ff-aa990dda7baf.png)

**Comment by a-deriabin** [comment]
![image](https://user-images.githubusercontent.com/2338967/74024067-16939b00-49b2-11ea-9dd2-30338fb6e224.png)

**Comment by a-deriabin** [comment]
![image](https://user-images.githubusercontent.com/2338967/74025522-2eb8e980-49b5-11ea-9111-2765273110fa.png)

**Comment by JustRevolt** [comment]
@Aeeee @nikaalin @ChirkinaTanya 
1. Заменить название таблицы Order (зарезервированное имя)
2. Свойство Issuer_id  в таблице Invoice убрать, так как его можно вытащить и таблицы Order
3. Обсудить 
> Схема с таблицей с одним полем, конечно, имеет право на жизнь, но обойтись лучше без нее. Когда я говорил, что надо поправить, то надо было или убрать isAdmin, но оставить полностью таблицу или наоборот. В целом, лучше занести данные о роли пользователя в таблицу с ним, а роли выделить в отдельную таблицу, потому что их может быть немного больше, чем просто Admin/Regular_user
4. Убрать связь между Car и Car_damage
> JOIN через одну таблицу не ухудшит ни удобство, ни скорость поиска
5. Обсудить 
> Несколько повреждений на заказ по машине - это хорошо, но в целях упрощения жизни предлагаем сделать одно повреждение на заказ, куда будут сразу описываться все недостатки при приеме от клиента.

**Comment by a-deriabin** [comment]
![image](https://user-images.githubusercontent.com/2338967/74081338-ee15aa80-4a5e-11ea-96f3-836e8ad96405.png)

**Comment by JustRevolt** [comment]
@Aeeee 
1. Переименовать Price_modifier в Orders на что-то похожее на купон или дополнительная скидка.
_Предложение: discount_
2. Добавить свойство "Репутация" в Users
3. Удалить Type в Car_damage (не имеет смысла, т.к. в одной записи хранятся много повреждений и не type не является информативным)

**Comment by a-deriabin** [comment]
![image](https://user-images.githubusercontent.com/2338967/74146559-607abc00-4c12-11ea-9530-b6dc13a92027.png)

**Comment by a-deriabin** [comment]
![изображение](https://user-images.githubusercontent.com/2338967/74326707-ebd38900-4d9b-11ea-9f30-42cb063da759.png)
