### ISSUE TITLE
Draw application diagram

### ISSUE THREAD

**Issue by Wedds** [java-practice-spb-2020/epam-ifmo-java-practice-2020-2#5]
Предложить сруктуру веб-страниц сервиса и продумать необходимые для ее реализации endpointы API.

**Comment by JustRevolt** [comment]
![Sitemap](https://user-images.githubusercontent.com/38432080/74358651-e04f8480-4dd2-11ea-8b94-e14d25efda19.png)

**Comment by JustRevolt** [comment]
**Sitemap-Detailed**
![Sitemap-Detailed-v1](https://user-images.githubusercontent.com/38432080/74423810-ed678480-4e61-11ea-9a25-7550a6e4c299.png)

**Comment by JustRevolt** [comment]
**Sitemap-Api endpoints**
![Sitemap-Api endpoints](https://user-images.githubusercontent.com/38432080/74423972-315a8980-4e62-11ea-8a6f-062f6067fc81.png)

**Comment by JustRevolt** [comment]
- [x] Удалить документы у админа

- [x] Заменить подтверждение документов на наличие

- [x] Удалить комментарии к подтверждениям

- [x] Заменить endpoints на более читаемые

**Comment by JustRevolt** [comment]
**Sitemap-Detailed**
![Sitemap-Detailed-v2](https://user-images.githubusercontent.com/38432080/74520168-14888980-4f28-11ea-9277-6fd08b633821.png)

**Comment by JustRevolt** [comment]
**Sitemap-Api endpoints**
![Sitemap-Api endpoints-v2](https://user-images.githubusercontent.com/38432080/74520243-32ee8500-4f28-11ea-84a1-007c246be709.png)

**Comment by JustRevolt** [comment]
**Sitemap-Detailed**
![Sitemap-Detailed-v3](https://user-images.githubusercontent.com/38432080/74533338-60e0c300-4f42-11ea-84fa-8b2260a67c5d.png)

**Comment by JustRevolt** [comment]
**Sitemap-Api endpoints**
![Sitemap-Api endpoints-v3](https://user-images.githubusercontent.com/38432080/74533379-7c4bce00-4f42-11ea-8e69-f7c403d72bd8.png)

**Comment by JustRevolt** [comment]
**Sitemap-Detailed**
![Sitemap-Detailed-v4](https://user-images.githubusercontent.com/38432080/74649103-fc1aa800-518f-11ea-9ba3-d4ed19dd0e04.png)

**Comment by JustRevolt** [comment]
**Sitemap-Api endpoints**
![Sitemap-Api endpoints-v4](https://user-images.githubusercontent.com/38432080/74649787-4f412a80-5191-11ea-84b8-0eca153672ec.png)
